"""make employee onboarding optional fields nullable

Revision ID: 5196c111bc8f
Revises: 8aaeaa2eb7f6
Create Date: 2026-04-03 14:47:38.212505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5196c111bc8f'
down_revision: Union[str, Sequence[str], None] = '8aaeaa2eb7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_users', 'bank_account_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_users', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_users', 'branch_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_users', 'ifsc_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_users', 'ifsc_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_users', 'branch_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_users', 'bank_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_users', 'bank_account_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
