"""add terms_conditions and privacy_policy tables

Revision ID: 8aaeaa2eb7f6
Revises: d017fe79cc15
Create Date: 2026-04-03 14:07:26.745261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aaeaa2eb7f6'
down_revision: Union[str, Sequence[str], None] = 'd017fe79cc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_header', sa.String(), nullable=False),
    sa.Column('policy_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_privacy_policy_id'), 'privacy_policy', ['id'], unique=False)
    op.create_table('terms_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_headline', sa.String(), nullable=False),
    sa.Column('term_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_conditions_id'), 'terms_conditions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terms_conditions_id'), table_name='terms_conditions')
    op.drop_table('terms_conditions')
    op.drop_index(op.f('ix_privacy_policy_id'), table_name='privacy_policy')
    op.drop_table('privacy_policy')
    # ### end Alembic commands ###
