"""updated documentation table

Revision ID: c2a181b9fcb1
Revises: a1dc48a5e683
Create Date: 2026-04-03 19:18:09.529442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a181b9fcb1'
down_revision: Union[str, Sequence[str], None] = 'a1dc48a5e683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation', sa.Column('doc_header', sa.String(), nullable=False))
    op.add_column('documentation', sa.Column('doc_description', sa.String(), nullable=False))
    op.drop_column('documentation', 'file_url')
    op.drop_column('documentation', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('documentation', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('documentation', 'doc_description')
    op.drop_column('documentation', 'doc_header')
    # ### end Alembic commands ###
