"""Add current_location table

Revision ID: d017fe79cc15
Revises: 7fceb44bd729
Create Date: 2026-04-01 01:21:27.006514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd017fe79cc15'
down_revision: Union[str, Sequence[str], None] = '7fceb44bd729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_location',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.admin_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_users.employee_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_current_location_date'), 'current_location', ['date'], unique=False)
    op.create_index(op.f('ix_current_location_location_id'), 'current_location', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_location_location_id'), table_name='current_location')
    op.drop_index(op.f('ix_current_location_date'), table_name='current_location')
    op.drop_table('current_location')
    # ### end Alembic commands ###
